SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
       MAX_SIZE - E.SIZE_OF_COLONY AS DEVIATION,
       E.ID
FROM ECOLI_DATA E
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS Y,
           MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) M ON YEAR(E.DIFFERENTIATION_DATE) = M.Y
ORDER BY YEAR ASC, DEVIATION ASC