SELECT 
    FISH_INFO.ID,
    FISH_NAME_INFO.FISH_NAME, 
    FISH_INFO.LENGTH 
FROM FISH_INFO
INNER JOIN FISH_NAME_INFO
    ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE (FISH_INFO.FISH_TYPE, FISH_INFO.LENGTH) IN (
    SELECT fi.FISH_TYPE, MAX(fi.LENGTH)
    FROM FISH_INFO fi
    GROUP BY fi.FISH_TYPE
)
ORDER BY 1;